### ISSUE TITLE
BeReal signatures are no longer valid.

### ISSUE THREAD

**Issue by 0utplay** [retoheusser/happy-headers#5]
Hi, today I started experiencing some issues with the provided device-id and bereal-signature. I noticed that the app now sends a different signature for each request and therefore I think that the requests stored in this repository are not working anymore.

I started doing some investigation on how the signature is calcluated but did not get that far. Maybe you can re-check if the signature algo changed

**Comment by retoheusser** [comment]
The signatures are still working, I'm using them everyday and hence testing it.
You are right that the app sends a different signature each time, because it computes them on the client with the timestamp as one of its parameters. But the server accepts signatures for a period of exactly one week, before it rejects them. That's why the same pre-computed signature works for an entire week in third-party clients.

**Comment by 0utplay** [comment]
Okay, maybe there is another issue on my side. I will have a look. Thank you

**Comment by 0utplay** [comment]
Its indeed working. Thanks
